bookers/config/routes.rb
Rails.application.routes.draw do

  get '/' => 'home#top'

  root 'home#top'

  get 'home/about' => 'home#about'

  devise_for :users

  #root 'books#index'

  resources :books, only: [:new, :create, :index, :show, :destroy, :edit, :update]

  resources :users, only: [:show, :edit, :index, :update]

end

bookers/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

bookers/app/models/book.rb
class Book < ApplicationRecord

	belongs_to :user

	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}

end

bookers/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :books, dependent: :destroy

         attachment :profile_image


  validates :name, presence: true, length: {minimum: 2, maximum: 20}
  validates :introduction, length: { maximum: 50}

end

bookers/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	before_action :configure_permitted_parameters, if: :devise_controller?

	#ログイン後
	def after_sign_in_path_for(resource)
  		user_path(current_user.id)
	end

	#ログアウト後
	def after_sign_out_path_for(resource)
  		root_path
	end

  	protected

	def configure_permitted_parameters
    	devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
    	devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
	end
end

bookers/app/controllers/books_controller.rb
class BooksController < ApplicationController

	before_action :authenticate_user!

	def new
		@book = Book.new
	end

	def create
	    @book = Book.new(book_params)
	    @book.user_id = current_user.id
	    if @book.save
	    	redirect_to book_path(@book), notice: "You have creatad book successfully."
	    else
	    	@books = Book.all
			@user = User.find_by(params[:id])
	    	render("books/index")
	    end
	end

	def index
		@books = Book.all
		@book = Book.new
		@user = current_user
	end

	def show
		@book = Book.find(params[:id])
		@book_form = Book.new
		@user = User.find_by(id: @book.user_id)
	end

	def destroy
	    @book = Book.find(params[:id])
	    @book.destroy
	    redirect_to books_path
	end

	def edit
		@book = Book.find(params[:id])
		if @book.user.id != current_user.id
			redirect_to books_path
		end
	end

	def update
		@book = Book.find(params[:id])
		if @book.update(book_params)
			redirect_to book_path(@book.id), notice: "You have creatad book successfully."
		else
			
			render("books/edit")
		end
	end

	private
    def book_params
        params.require(:book).permit(:title, :body)
    end
end

bookers/app/controllers/home_controller.rb
class HomeController < ApplicationController
	def top

	end

	def about

	end
end

bookers/app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
	  @book = Book.new
    @books = @user.books.page(params[:page]).reverse_order
  end

  def edit
  	@user = User.find(params[:id])
    if @user.id != current_user.id
      redirect_to user_path(current_user.id)
    end
  end

  def index
  	@users = User.all
  	@book = Book.new
    @user = current_user
  end

  def update
  	@user = User.find(params[:id])
  	@user_id = current_user.id
  	if @user.update(user_params)
  		redirect_to user_path(@user.id), notice: "You have updated user successfully."
    else
      render("users/edit")
  	end
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

bookers/app/helpers/application_helper.rb
module ApplicationHelper
end

bookers/app/helpers/books_helper.rb
module BooksHelper
end

bookers/app/helpers/home_helper.rb
module HomeHelper
end

bookers/app/helpers/users_helper.rb
module UsersHelper
end

bookers/app/views/books/_list.html.erb
<h2>New book</h2>

<%= form_for(@book) do |f| %>

    <div class="field row">
      <label for="book_title">Title</label>
    	<%= f.text_field :title,class:"book_title col-xs-12" %>
    </div>

    <div class="field row">
      <label for="book_body">Option</label>
    	<%= f.text_area :body,class:"book_body col-xs-12" %>
    </div>

    <div class="field row">
    	<%= f.submit 'Create Book' , class:"btn btn-primary col-xs-12" %>
    </div>

<% end %>

bookers/app/views/books/edit.html.erb
<div class="col-md-6 col-md-offset-3">

    <h1>Editing Book</h1>

    <% if @book.errors.any? %>
        <div id="error_explanation">
          <h3 style="color: red"><%= @book.errors.count %>error prohibited this obj from being saved:</h3>
          <ul>
          <% @book.errors.full_messages.each do |message| %>
            <li style="color: red"><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>


    <%= form_for(@book) do |f| %>
        <div class="field row">
            <label for="book_title">Title</label>
            <%= f.text_field :title, class:"col-xs-12" %>
        </div>
        <div class="field row">
            <label for="book_body">Option</label>
            <%= f.text_area :body, class:"col-xs-12" %>
        </div>

        <div class="action row" id="Update">
            <%= f.submit 'Update Book', class:"btn btn-primary col-xs-12" %>
        </div>
    <% end %>

    <%=link_to 'Show', book_path(@book.id),class:"show_#{@book.id}" %><span class="esikiri">|</span><%=link_to 'Back', "/books/",class:"back" %>
</div>

bookers/app/views/books/index.html.erb
	  <% if @book.errors.any? %>
        <div id="error_explanation">
          <h3 style="color: red"><%= @book.errors.count %>error prohibited this obj from being saved:</h3>
          <ul>
          <% @book.errors.full_messages.each do |message| %>
            <li style="color: red"><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>



<div class="col-xs-3">

	<%= render 'users/list', user: @user %>

    <%= render 'books/list', book: @book %>

  </div>

<div class="col-xs-9">
	<h2>Books</h2>

	    <table class="table table-hover table-inverse">
		  <thead>
		    <tr>
		      <th></th>
		      <th>Title</th>
		      <th>Opinion</th>
		      <th colspan="3"></th>
		    </tr>
		  </thead>

		  <tbody>
		  	<% @books.each do |f| %>
		      <tr>
		        <td>
		        	<%= link_to user_path(f.user_id) do %>
		        		<%= attachment_image_tag f.user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %>
		        	<% end %>
		        </td>
		        <td>
		        	<%= link_to f.title, book_path(f.id) %>
		        </td>
		        <td>
		        	<%= f.body %>
		        </td>
		      </tr>
		    <% end %>
		  </tbody>
		</table>
</div>

bookers/app/views/books/new.html.erb
<h2>New book</h2>

<%= form_for(@book) do |f| %>

      <% if @book.errors.any? %>
        <div id="error_explanation">
          <h2><%= @book.errors.count %>件のエラーが発生しました。</h2>
          <ul>
          <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

    <h4>Title</h4>
    <div>
    	<%= f.text_field :title,class:"book_title" %>
    </div>

    <h4>Body</h4>
    <div>
    	<%= f.text_area :body,class:"book_body" %>
    </div>

    <div>
    	<%= f.submit 'Create Book' %>
    </div>

<% end %>

bookers/app/views/books/show.html.erb
  <p id="notice" style="color: green;">
    <% if flash[:notice] %>
      <%= flash[:notice] %>
    <% end %>
  </p>

  <div class="col-xs-3">

    <%= render 'users/list', user: @user %>

    <%= render 'books/list', book: @book_form %>

  </div>

    <div class="col-xs-9">
    		<h2>Book detail</h2>
    		<table class="table">
    		  <tbody>
            <tr>
              <td>
                <%= link_to user_path(@book.user.id) do %>
                  <%= attachment_image_tag @user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %><br>
                  <%= @book.user.name %>
                <% end %>
              </td>
              <td>
                <%= @book.title %>
              </td>
              <td>
                <%= @book.body %>
              </td>

              <td>
                <% if @book.user == current_user %>
                  <%= link_to "Edit" , edit_book_path(@book.id), class:"btn-sm btn-success" %>
                <% end %>
              </td>
              <td>
                <% if @book.user == current_user %>
                  <%= link_to "Destroy", book_path(@book), method: :delete, class:"btn-sm btn-danger" %>
                <% end %>
              </td>
            </tr>
          </tbody>
        </table>
      </div>

bookers/app/views/home/about.html.erb
<div class="container">

        <p id="notice"></p>


      	<h1>Welcome to <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>!</h1>


      </div>

bookers/app/views/home/top.html.erb
<div class="container">
  <p id="notice" style="color: green;">
    <% if flash[:notice] %>
      <%= flash[:notice] %>
    <% end %>
  </p>
  <div class="row">
    <div class="top-message col-md-offset-3 col-md-6">
      <h1>welcome to <span class="glyphicon glyphicon-book"><strong>Bookers</strong>  !!</span></h1>
        <p>In  <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>, </p>
        <p>you can share and exchange  your opinions , inpressions , and emotions</p>
        <p> about varioius books!</p>

      <div class="btn-wrapper">
        <div class="row">
         <p><a class="btn btn-info col-xs-10 col-xs-offset-1 sign_in" href="/users/sign_in">Log in</a></p>
        </div>
        <div class="row">
        <p><a class="btn btn-success col-xs-10 col-xs-offset-1 sign_up" href="/users/sign_up">Sign Up</a></p>
        </div>
      </div>
    </div>
  </div>
</div>

bookers/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav class="nav navbar-nav navbar-left">
      <span>Bookers</span>
    </nav>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li>
            <%= link_to ' Home', user_path(current_user.id), class:"glyphicon glyphicon-home home" %>
          </li>
          <li>
            <%= link_to ' Users', users_path, class:"glyphicon glyphicon-user users" %>
          </li>
          <li>
            <%= link_to ' Books', books_path, class:"glyphicon glyphicon-home home" %>
            <!--a class="glyphicon glyphicon-book books" href="/books"> Books</a--></li>
          <li>
            <a class="glyphicon glyphicon-log-out logout" rel="nofollow" data-method="delete" href="/users/sign_out"> logout</a>
          </li>
        <% else %>
          <li><a class="glyphicon glyphicon-home home" href="/"> Home</a></li>
          <li>
            <a class="glyphicon glyphicon-link about" href="/home/about"> About</a>
          </li>
          <li>
            <a class="glyphicon glyphicon-edit sign_up" href="/users/sign_up"> sign up</a>
          </li>
          <li>
            <a class="glyphicon glyphicon-log-in sign_in" href="/users/sign_in"> login</a>
          </li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>


  <body>


    <div class="container">
      <div class="row">

    <%= yield %>

      </div>
    </div>
  </body>

  <footer>
    <div class="container">
      <div class="row">
        <div class="col-xs-3 col-xs-offset-9">
          <p>CopyRight Infratop.inc</p>
        </div>
      </div>
    </div>
  </footer>
</html>

bookers/app/views/users/_list.html.erb
	<h2>User info</h2>
	<% if user.present? %>
	<%= attachment_image_tag user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "100x100" %>
		  <table class="table">
			<tbody>
				<tr></tr>
				<tr>
					<th>name</th>
					<th><%= user.name %></th>
				</tr>
				<tr>
					<th>introduction</th>
					<th><%= user.introduction %></th>
				</tr>
			</tbody>
		  </table>
	<% end %>

		  <% if user.present? %>
		  <div class="row">
  				<%= link_to "", edit_user_path(user.id), class:"col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>
  		  </div>
		  <% end %>

bookers/app/views/users/edit.html.erb
<div class="container">

  <p id="notice" style="color: green">
    <% if flash[:notice] %>
      <%= flash[:notice] %>
    <% end %>
  </p>

  <h2>User info</h2>

      <% if @user.errors.any? %>
        <div id="error_explanation">
          <h3 style="color: red"><%= @user.errors.count %>error prohibited this obj from being saved:</h3>
          <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li style="color: red"><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

  <%= form_for(@user) do |f| %>

    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name, autofocus: true %>
    </div>

    <div class="field">
      <%= f.label :image %>
      <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "user-edit-form" %>
    </div>

  <div class="field">
    <%= f.label :introduction %>
    <%= f.text_area :introduction, autofocus: true %>
  </div>



  <%= f.submit "Update User" %>
  <% end %>
</div>

bookers/app/views/users/index.html.erb
    <div class="col-xs-3">

      <%= render 'users/list', user: @user %>

      <%= render 'books/list', book: @book %>

    </div>

    <div class="col-xs-9">

    <h2>Users</h2>

    <table class="table">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% if @users.present? %>
    <% @users.each do |f| %>
      <tr>
        <td>
          <%= attachment_image_tag f, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %>
        </td>
        <td><%= f.name %></td>
        <td><%= link_to 'Show', user_path(f.id) %></td>
      </tr>
    <% end %>
    <% end %>
  </tbody>
</table>

  </div>

bookers/app/views/users/show.html.erb
<% paginate @books, class: "paginate" %>

	  <% if @book.errors.any? %>
        <div id="error_explanation">
          <h3 style="color: red"><%= @book.errors.count %>error prohibited this obj from being saved:</h3>
          <ul>
          <% @book.errors.full_messages.each do |message| %>
            <li style="color: red"><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>



<p id="notice" style="color: green;">
    <% if flash[:notice] %>
      <%= flash[:notice] %>
    <% end %>
  </p>

<div class="col-xs-3">

	<%= render 'users/list', user: @user %>

    <%= render 'books/list', book: @book %>

</div>

<div class="col-xs-9">
	<h2>Books</h2>

	    <table class="table table-hover table-inverse">
		  <thead>
		    <tr>
		      <th></th>
		      <th>Title</th>
		      <th>Opinion</th>
		      <th colspan="3"></th>
		    </tr>
		  </thead>

		  <tbody>
		  	<% @books.each do |f| %>
		      <tr>
		        <td>
		        	<%= attachment_image_tag f.user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %>
		        </td>
		        <td>
		        	<%= link_to f.title, book_path(f.id) %>
		        </td>
		        <td>
		        	<%= f.body %>
		        </td>
		      </tr>
		    <% end %>
		  </tbody>
		</table>
</div>